use crate::common::*;

#[derive(Builder, Clone, Serialize, Deserialize, Debug, Getters, new)]
#[getset(get = "pub", set = "pub")]
pub struct MetricInfo {
    pub timestamp: String,
    pub host: String,
    pub name: String,
    pub jvm_usage: i64,
    pub cpu_usage: i64,
    pub disk_usage: i64,
    pub jvm_young_usage_byte: i64,
    pub jvm_old_usage_byte: i64,
    pub jvm_survivor_usage_byte: i64,
    pub query_cache_hit: f64,
    pub cache_memory_size: i64,
    pub os_swap_total_in_bytes: i64,
    pub os_swap_usage: f64,
    pub http_current_open: i64,
    pub node_shard_cnt: i64,
    pub indexing_latency: f64,
    pub query_latency: f64,
    pub fetch_latency: f64,
    pub translog_operation: i64,
    pub translog_operation_size: i64,
    pub translog_uncommited_operation: i64,
    pub translog_uncommited_operation_size: i64,
    pub flush_total: i64,
    pub refresh_total: i64,
    pub refresh_listener: i64,
    pub inflight_requests: i64,
    pub search_active_thread: u32,
    pub search_thread_queue: u32,
    pub search_rejected_thread: u32,
    pub write_active_thread: u32,
    pub write_thread_queue: u32,
    pub write_rejected_thread: u32,
    pub bulk_active_thread: u32,
    pub bulk_thread_queue: u32,
    pub bulk_rejected_thread: u32,
    pub get_active_thread: u32,
    pub get_thread_queue: u32,
    pub get_rejected_thread: u32,
    pub menagement_active_thread: u32,
    pub menagement_thread_queue: u32,
    pub menagement_rejected_thread: u32,
    pub generic_active_thread: u32,
    pub generic_thread_queue: u32,
    pub generic_rejected_thread: u32,
}
